# Generated by Django 3.2.7 on 2021-09-14 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_News', '0002_auto_20210914_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_News.category'),
        ),
    ]
