# Generated by Django 3.2.7 on 2021-09-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_News', '0006_auto_20210915_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
