# Generated by Django 3.2.7 on 2021-09-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_News', '0008_news_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='thumbnail/'),
        ),
    ]
