# Generated by Django 3.2.7 on 2021-09-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_News', '0009_news_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
