# Generated by Django 3.2.7 on 2021-09-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_News', '0010_news_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='language',
            field=models.CharField(choices=[('bn', 'bangla'), ('en', 'english'), ('ar', 'arebic')], default='en', max_length=20),
        ),
    ]
