# Generated by Django 3.2.7 on 2021-09-15 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_News', '0011_news_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='love',
            field=models.ManyToManyField(blank=True, related_name='love', to=settings.AUTH_USER_MODEL),
        ),
    ]
