# Generated by Django 3.2.7 on 2021-09-15 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_News', '0012_auto_20210915_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='love',
        ),
        migrations.AddField(
            model_name='news',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
