# Generated by Django 3.2.7 on 2021-09-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_News', '0017_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
