# Generated by Django 3.2.7 on 2021-09-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_News', '0020_remove_news_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
