# Generated by Django 3.2.7 on 2021-09-19 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_News', '0023_alter_news_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
