# Generated by Django 3.2.7 on 2021-09-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_News', '0029_categoryapply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
