# Generated by Django 3.2.7 on 2021-09-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_News', '0031_subcategoryapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_nav',
            field=models.BooleanField(default=False),
        ),
    ]
