# Generated by Django 3.2.7 on 2021-09-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_News', '0032_category_is_nav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliderimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='Slider/')),
            ],
        ),
    ]
