# Generated by Django 3.2.7 on 2021-09-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorlist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
